doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
        types:
            userId: App\Infra\User\Doctrine\Types\UserIdType

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true

        mappings:
            User:
                type: xml
                prefix: App\Domain\User\Model
                dir: '%kernel.project_dir%/config/modules/User/persistence/Model'
                is_bundle: false
            Security:
                type: xml
                prefix: App\Domain\Security\ValueObject
                dir: '%kernel.project_dir%/config/modules/Security/persistence/ValueObject'
                is_bundle: false
