version: '3.7'
services:
    db:
        container_name: db
        image: mysql
        command: ["--default-authentication-plugin=mysql_native_password"]
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
        networks:
            - db
    php:
        container_name: php-fpm
        build: ./php-fpm
        ports:
            - "9000:9001"
        volumes:
            - ../../../:/var/www/symfony:cached
            - ../../../logs/symfony:/var/www/symfony/var/log:cached
        depends_on: 
            - db
        networks:
            - db
            - php
    nginx:
        container_name: nginx
        build: ./nginx
        ports:
            - "8080:80"
        depends_on: 
            - php
        networks:
            - php
        volumes:
            - ../../../logs/nginx:/var/log/nginx:cached
            - ../../../:/var/www/symfony:cached
    elasticsearch:
        container_name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
        environment:
            - discovery.type=single-node
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ports:
            - "9200:9200"
        networks:
            elk_stack:
                aliases:
                    - "elasticsearch"
    logstash:
        container_name: logstash
        image: docker.elastic.co/logstash/logstash:7.4.2
        depends_on: 
            - elasticsearch
        volumes:
            - ./elk/logstash/pipelines.yml:/usr/share/logstash/config/pipelines.yml:cached
            - ./elk/logstash/conf.d:/etc/logstash/conf.d:cached
            - ../../../logs/symfony:/var/www/symfony/var/log:cached
            - ../../../logs/nginx:/var/log/nginx:cached
        networks:
            - elk_stack
    kibana:
        container_name: kibana
        depends_on: 
            - elasticsearch
        image: docker.elastic.co/kibana/kibana:7.5.1
        networks:
            - elk_stack
        ports:
            - "81:5601"
    rmq:
        image: rabbitmq:3-management
        environment:
            RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
            RABBITMQ_DEFAULT_USER: "guest"
            RABBITMQ_DEFAULT_PASS: "guest"
            RABBITMQ_DEFAULT_VHOST: "/"
        ports:
            - "15672:15672"
        networks:
            - php
        depends_on:
            - php
    mailhog:
        image: mailhog/mailhog
        ports:
            - "8025:8025"
        networks:
            - php
        depends_on:
            - php
networks:
    db:
    php:
    elk_stack:
